### PR TITLE
Add file extensions

### PR DESCRIPTION
**Pull request by chege4179**
This PR introduces file icons for nest js decorators and dto( Data Transfer Objects) files 
e.g user.decorator.ts and login.dto.ts

### CODE REVIEW

**Comment by chege4179** [comment]
@dinbtechit

**Comment by dinbtechit** [comment]
@chege4179  - Thank you for your contribution. I just have couple of concerns with this change. Firstly decorators are typescript functionality and it's not part of nestjs per se, I dont think it would be appropriate for this package to provide a fileIcon for that. And, Secondly, I don't like the idea of using Gateway's Icon for decorators. It could cause confusion.

Open to thoughts. Cheers mate!

**Comment by chege4179** [comment]
Ok I just thought having a file icon for custom decorators and dto files in nest js would be good .. The choice of file icons was completely random ..I just picked from the least used aspects of nest js

**Comment by dinbtechit** [comment]
Sorry closing this PR. As this is not aligned with nestJS.

**Pull request closed without merging**
